FROM php:7.4.3-apache

WORKDIR /var/www

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV APACHE_DOCUMENT_ROOT /var/www

RUN apt update -y && apt dist-upgrade -y && apt install curl libcurl4-gnutls-dev gnuplot gnuplot-nox git libzip-dev -y && apt-get clean -y
RUN docker-php-ext-install mysqli curl pdo_mysql zip 

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN a2enmod rewrite

COPY . .
#RUN chown -R www-data:www-data /var/www
RUN chmod -R 777 /var/www/cache
#USER www-data

VOLUME /var/www/cache

RUN php composer.phar install


