# Generated by Django 4.1 on 2022-09-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='wiki/'),
        ),
    ]
