# Generated by Django 4.1 on 2022-09-26 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_wiki_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='wiki.wiki')),
            ],
        ),
    ]
