{
 "title": "Состояние внешних портов WEGABOX",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "database", "label": "Выбор системы", "query": "mysql" }
  ]
 },
 "panels": [
  {
   "title": "DRV1 текущее состояние",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -1, 1)*1 as 'A'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -2, 1)*1 as 'B'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -3, 1)*1 as 'C'\nfrom sens\nWHERE $__timeFilter(dt)\n\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -4, 1)*1 as 'D'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "DRV1 диаграмма",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 13, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -1, 1)*1 as 'A'\nfrom sens\nWHERE $__timeFilter(dt)\n\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -2, 1)*1 as 'B'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -3, 1)*1 as 'C'\nfrom sens\nWHERE $__timeFilter(dt)"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -4, 1)*1 as 'D'\nfrom sens\nWHERE $__timeFilter(dt)"
    }
   ]
  },
  {
   "title": "ШИМ портов A и B",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(dt) as time_sec, \n  PWD1\nFROM sens\nWHERE $__timeFilter(dt)\n\n"
    }
   ]
  },
  {
   "title": "DRV2 текущее состояние",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -5, 1)*1 as 'A'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -6, 1)*1 as 'B'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -7, 1)*1 as 'C'\nfrom sens\nWHERE $__timeFilter(dt)\n\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -8, 1)*1 as 'D'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "DRV2 диаграмма",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 13, "x": 3, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -5, 1)*1 as 'A'\nfrom sens\nWHERE $__timeFilter(dt)\n\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -6, 1)*1 as 'B'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -7, 1)*1 as 'C'\nfrom sens\nWHERE $__timeFilter(dt)"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -8, 1)*1 as 'D'\nfrom sens\nWHERE $__timeFilter(dt)"
    }
   ]
  },
  {
   "title": "DRV3 текущее состояние",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -9, 1)*1 as 'A'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -10, 1)*1 as 'B'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -11, 1)*1 as 'C'\nfrom sens\nWHERE $__timeFilter(dt)\n\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -12, 1)*1 as 'D'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "DRV3 диаграмма",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 13, "x": 3, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -9, 1)*1 as 'A'\nfrom sens\nWHERE $__timeFilter(dt)\n\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -10, 1)*1 as 'B'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -11, 1)*1 as 'C'\nfrom sens\nWHERE $__timeFilter(dt)"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -12, 1)*1 as 'D'\nfrom sens\nWHERE $__timeFilter(dt)"
    }
   ]
  },
  {
   "title": "ШИМ портов C и D",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(dt) as time_sec, \n  PWD2\nFROM sens\nWHERE $__timeFilter(dt)\n\n"
    }
   ]
  },
  {
   "title": "DRV4 текущее состояние",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -13, 1)*1 as 'A'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -14, 1)*1 as 'B'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -15, 1)*1 as 'C'\nfrom sens\nWHERE $__timeFilter(dt)\n\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -16, 1)*1 as 'D'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "DRV4 диаграмма",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 13, "x": 3, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -13, 1)*1 as 'A'\nfrom sens\nWHERE $__timeFilter(dt)\n\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -14, 1)*1 as 'B'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -15, 1)*1 as 'C'\nfrom sens\nWHERE $__timeFilter(dt)"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nSUBSTRING(bin(if(readGPIO is null,0,readGPIO)), -16, 1)*1 as 'D'\nfrom sens\nWHERE $__timeFilter(dt)"
    }
   ]
  }
 ]
}