{
 "title": "WEGA-SERVER",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "database", "label": "Выбор системы", "query": "mysql" },
   { "name": "logfilter" }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT value, comment\nFROM config\nwhere parameter=\"namesys\"\n;"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nif(AirTemp != 0,AirTemp,null) as 'Воздуха'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nif(RootTemp != -127 and RootTemp != 85,RootTemp,null) as 'корней'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nftr(NTC) as 'расвтора'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "pH растора",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\npH(pHmV) as 'pH раствора'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "Контроль корневого давления",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nif(AirTemp != 0,AirTemp,null)-if(RootTemp != -127 and RootTemp != 85,RootTemp,null) as 'Разница температур воздуха и корней'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "Влажность воздуха",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nAirHum as 'Влажность'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "EC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nif ( ftr(NTC) is null, null,EC(Ap,An,ftr(NTC))) as 'EC раствора'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    },
    {
     "rawSql": "SELECT (value * 1) as 'max'\nFROM config  WHERE parameter=\"ECPlan\""
    }
   ]
  },
  {
   "title": "Помпа циркуляции раствора",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nif(readGPIO is null,false,true)\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "Уровень раствора",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nintpl(levmin(Dist)) as 'Остаток раствора в литрах'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "Лог контроллера",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(datetime) AS \"time\",\n  SUBSTRING_INDEX(msg,\"s \",1) AS \"uptime\",\n  SUBSTRING_INDEX(msg,\"s \",-1) AS \"value\"\n  \nFROM syslog.logs\nWHERE\n  $__timeFilter(datetime)\n  and host=\"${database}\"\n  and msg LIKE '%${logfilter}%'\norder by datetime desc, SUBSTRING_INDEX(msg,\"s \",-1)*1 desc "
    }
   ]
  },
  {
   "title": "Объем внесенной воды для коррекции ЕС",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nECStabOn\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  },
  {
   "title": "Water Level",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nintpl(levmin(Dist)) as 'Water Level'\nfrom sens\nWHERE $__timeFilter(dt)"
    },
    {
     "rawSql": "SELECT (value * 1) as 'Max'\nFROM config  WHERE parameter=\"LevelFull\""
    }
   ]
  },
  {
   "title": "Контроль циркуляции",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(dt) as 'time',\nif(RootTemp != -127 and RootTemp != 85,RootTemp,null)-ftr(NTC) as 'Разница температуры корней и бака'\nfrom sens\nWHERE $__timeFilter(dt)\n"
    }
   ]
  }
 ]
}