# Generated by Django 4.1 on 2022-08-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Micro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Имя профиля')),
                ('ec', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Ec')),
                ('ppm', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='PPM')),
                ('n', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='N')),
                ('no3', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='NO3')),
                ('nh4', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='NH4')),
                ('p', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='P')),
                ('k', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='K')),
                ('ca', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Ca')),
                ('mg', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Mg')),
                ('s', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='S')),
                ('cl', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Cl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('macro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='calc.macro')),
                ('micro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='calc.micro')),
                ('plant_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='calc.plantprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
