# Generated by Django 4.1 on 2022-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20220831_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantprofile',
            name='mixer_ip',
            field=models.CharField(default='mixer.local', max_length=1024, verbose_name='Адрес/порт миксера'),
        ),
        migrations.AddField(
            model_name='plantprofile',
            name='mixer_system_number',
            field=models.FloatField(default=1, verbose_name='Номер системы куда нальется раствор'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='micro_calc_mode',
            field=models.CharField(choices=[('u', 'Все микро соли'), ('b', 'Комплекс по бору')], default='u', max_length=2, verbose_name='Микро метод расчета'),
        ),
    ]
