# Generated by Django 4.1 on 2022-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20220831_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='mixer_system_number',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Номер системы куда нальется раствор'),
        ),
    ]
