# Generated by Django 4.1 on 2022-09-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_plantprofile_mixer_system_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='p_b',
            field=models.FloatField(blank=True, default=0.3, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_cacl2',
            field=models.FloatField(blank=True, default=0.77, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_cano3',
            field=models.FloatField(blank=True, default=0.4, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_cmplx',
            field=models.FloatField(blank=True, default=0.27, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_co',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_cu',
            field=models.FloatField(blank=True, default=0.15, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_fe',
            field=models.FloatField(blank=True, default=0.05, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_k2so4',
            field=models.FloatField(blank=True, default=0.4, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_kh2po4',
            field=models.FloatField(blank=True, default=0.12, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_kno3',
            field=models.FloatField(blank=True, default=0.35, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_mgno3',
            field=models.FloatField(blank=True, default=0.32, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_mgso4',
            field=models.FloatField(blank=True, default=0.35, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_mn',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_mo',
            field=models.FloatField(blank=True, default=0.4, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_nh4no3',
            field=models.FloatField(blank=True, default=0.25, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_si',
            field=models.FloatField(blank=True, default=2.3, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='p_zn',
            field=models.FloatField(blank=True, default=0.4, null=True),
        ),
    ]
