# Generated by Django 4.1 on 2022-08-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_remove_micro_user_remove_userprofile_macro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantprofile',
            old_name='mgno3_mo3',
            new_name='mgno3_no3',
        ),
    ]
