# Generated by Django 4.1 on 2022-09-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_plantprofile_p_b_alter_plantprofile_p_cacl2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_from_template', to='calc.planttemplate'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.planttemplate'),
        ),
    ]
