# Generated by Django 4.1 on 2022-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_plantprofile_ca_alter_plantprofile_cl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='cacl2_ca',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='CaCl2_Ca'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='cacl2_cl',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='CaCl2_Cl'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='cano3_ca',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='CaNO3_Ca'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='cano3_nh4',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='CaNO3_NH4'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='cano3_no3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='CaNO3_NO3'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='k2so4_k',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='K2SO4_K'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='k2so4_s',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='K2SO4_S'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='kh2po4_k',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='KH2PO4_K'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='kh2po4_p',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='KH2PO4_P'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='kno3_k',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='KNO3_K'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='kno3_no3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='KNO3_NO3'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='mgno3_mg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='MgNO3_Mg'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='mgno3_no3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='MgNO3_NO3'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='mgso4_mg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='MgSO4_Mg'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='mgso4_s',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='MgSO4_S'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='nh4no3_nh4',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='NH4NO3_NH4'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='nh4no3_no3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='NH4NO3_NO3'),
        ),
    ]
