# Generated by Django 4.1 on 2022-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_alter_plantprofile_cacl2_ca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='b',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='co',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Co'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='cu',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Cu'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='fe',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Fe'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='mn',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Mn'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='mo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Mo'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='si',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Si'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='zn',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Zn'),
        ),
    ]
