# Generated by Django 4.1 on 2022-09-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20220908_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantprofilehistory',
            name='history_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='plantprofilehistory',
            name='history_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
