# Generated by Django 4.1 on 2022-09-13 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_plantprofilehistory_history_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantProfileShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.plantprofile')),
            ],
        ),
    ]
