# Generated by Django 4.1 on 2022-08-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_templates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='PlantTemplate',
        ),
    ]
