# Generated by Django 4.1 on 2022-09-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_plantprofilehistory_history_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantprofilehistory',
            name='history_image',
        ),
        migrations.RemoveField(
            model_name='plantprofilehistory',
            name='history_image2',
        ),
        migrations.RemoveField(
            model_name='plantprofilehistory',
            name='history_image3',
        ),
        migrations.RemoveField(
            model_name='plantprofilehistory',
            name='history_image4',
        ),
    ]
