# Generated by Django 4.1 on 2022-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_rename_templates_planttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttemplate',
            name='profile_owner',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Автор'),
        ),
    ]
