# Generated by Django 4.1 on 2022-08-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_planttemplate_profile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planttemplate',
            name='profile',
        ),
        migrations.AddField(
            model_name='plantprofile',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.planttemplate'),
        ),
    ]
