# Generated by Django 4.1 on 2022-08-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_remove_planttemplate_profile_plantprofile_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planttemplate',
            options={'ordering': ['name', 'profile_owner']},
        ),
        migrations.AddField(
            model_name='plantprofile',
            name='from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_from_template', to='calc.planttemplate'),
        ),
    ]
