# Generated by Django 4.1 on 2022-08-21 07:51

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_auto_20220820_1931'),
    ]

    operations = [
    
    ]
