# Generated by Django 4.1 on 2022-08-21 07:51

from django.db import migrations


def load_initial_data(apps, schema_editor):
    from django.core import serializers

    PlantProfile = apps.get_model('calc', 'PlantProfile')
    PlantTemplate = apps.get_model('calc', 'PlantTemplate')
    
    a = PlantProfile(user_id=1, ec=0, ppm=0)
    error=True
    counter = 0
    while error:
        try:
            a.save()
            error=False
        except Exception as e:
            error=True
            counter+=1
            if counter>100:
                import logging
                logging.exception(e)
                raise e
            pass
    a.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_auto_20220820_1931'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
