# Generated by Django 4.1 on 2022-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_auto_20220821_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofile',
            name='ec',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Ec'),
        ),
        migrations.AlterField(
            model_name='plantprofile',
            name='ppm',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='PPM'),
        ),
    ]
