# Generated by Django 4.1 on 2022-08-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_alter_plantprofile_ec_alter_plantprofile_ppm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile_data', models.JSONField(blank=True, null=True)),
                ('changed_data', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.plantprofile')),
            ],
        ),
    ]
