# Generated by Django 4.1 on 2022-08-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0018_plantprofilehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantprofilehistory',
            name='changed_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='plantprofilehistory',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
