# Generated by Django 4.1 on 2022-08-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_alter_plantprofilehistory_changed_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantprofilehistory',
            options={'ordering': ['pk', 'date']},
        ),
    ]
