# Generated by Django 4.1 on 2022-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0021_alter_plantprofile_b_alter_plantprofile_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantprofile',
            name='litres',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
